version: '3.9'

networks:
  backend:
    name: reseau-back
  frontend:
    name: reseau-front

services:
  database:
    image: mysql:latest
#    ports:
#      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: testdb
    networks:
      - backend
    volumes:
      - D:\formation\docker\ynov\volumes\datamysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: toor
      PMA_HOST: database
    depends_on:
      - database
    networks:
      - backend
      - frontend