version: '3.9'

services:
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: testdb

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: toor
      PMA_HOST: database